apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: mern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: hazemhashem100/backend:latest
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: node-app-config
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend
  namespace: mern
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
