apiVersion: batch/v1
kind: Job
metadata:
  name: backend-kaniko
  namespace: jenkins
spec:
  template:
    metadata:
      labels:
        app: backend-kaniko
    spec:
      containers:
      - name: backend-kaniko
        image: gcr.io/kaniko-project/executor:v1.6.0-debug
        args:
        - "--context=git://github.com/hazemhashem881/fullstack-shopping-cart.git"
        - "--git=branch=backend"
        - "--destination=hazemhashem100/backend:vlatest"
        - "--dockerfile=Dockerfile"
        volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      restartPolicy: Never
  backoffLimit: 2
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
