apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbkaniko
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: kaniko
  template:
    metadata:
      labels:
        app: kaniko
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      initContainers:
        - name: git-clone-db
          image: alpine/git
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /temp-workspace &&
              git clone --verbose --single-branch --branch=db https://github.com/hazemhashem881/fullstack-shopping-cart.git /temp-workspace &&
              rm -rf /workspace/* &&
              mv /temp-workspace/* /workspace &&
              chmod 777 /workspace


          volumeMounts:
            - name: git-repo-db
              mountPath: /workspace

      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:v1.6.0-debug
          imagePullPolicy: Always
          args:
            - "--context=/workspace"
            - "--destination=hazemhashem100/db:latest"
            - "--dockerfile=/workspace/Dockerfile"
          volumeMounts:
            - name: git-repo-db
              mountPath: /workspace
            - name: kaniko-secret
              mountPath: /kaniko/.docker

      volumes:
        - name: git-repo-db
          emptyDir: {}
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
