apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-kaniko
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: db-kaniko
  template:
    metadata:
      labels:
        app: db-kaniko
    spec:                                                 
      containers:
        - name: db-kaniko
          image: gcr.io/kaniko-project/executor:v1.6.0-debug
          args:
            - "--context=git://github.com/hazemhashem881/fullstack-shopping-cart.git"
            - "--git=branch=db"  # Replace <your-branch-name> with the specific branch you want to clone
            - "--destination=hazemhashem100/db:latest"
            - "--dockerfile=Dockerfile"
          volumeMounts:
            - name: kaniko-secret
              mountPath: /kaniko/.docker
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
