apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbkaniko
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: kaniko
  template:
    metadata:
      labels:
        app: kaniko
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=/workspace/"
            - "--destination=hazemhashem100/db:latest"
            - "--dockerfile=/workspace/Dockerfile"
          volumeMounts:
            - name: git-repo-db
              mountPath: /workspace
            - name: kaniko-secret
              mountPath: /kaniko/.docker
      initContainers:
        - name: git-clone
          image: alpine/git 
          args:
            - clone
            - --single-branch
            - --branch=db  
            - https://github.com/hazemhashem881/fullstack-shopping-cart.git
            - /workspace
          volumeMounts:
            - name: git-repo-db
              mountPath: /workspace

    
      volumes:
        - name: git-repo-db
          emptyDir: {}
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
