apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-db-pv
  namespace: mern
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db" 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mern
  name: mongo-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
