apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mern
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: mongo-db-pvc
 
      containers:
      - name: mongodb
        image: hazemhashem100/db
        volumeMounts:
          - name:  mongo-vol
            mountPath: /data/db
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: mongodb-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: mern
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
