apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
  namespace: mern

spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - name: front-app
        image: hazemhashem100/frontend
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontendsvc
  namespace: mern
spec:
  selector:
    app: front-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80  # Exposed port on the service
      targetPort: 3000  # Port your frontend application is listening on
      nodePort: 31000